apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: bcanignqf-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/bcanignqf-java-quarkus-gitops